INSERT INTO Genre (Nom_scientifique_genre,Nom_Francais_genre)
VALUES 
("Ailanthus","Ailante"),
("Amelanchier","Amélanchier"),
("Cercidiphyllum","Arbre à caramel"),
("Tetradium","Arbre à miel"),
("Albizia","Arbre à soie"),
("Ginkgo","Arbre aux quarante écus"),
("Cercis","Arbre de Judée"),
("Crataegus","Aubépine"),
("Alnus","Aulne"),
("Betula","Bouleau"),
("Catalpa","Catalpa"),
("Toona","Cedrele"),
("Carpinus","Charme"),
("Quercus","Chêne"),
("Clerodendrum","Clerodendron"),
("Liquidambar","Copalme"),
("Cupressus","Cyprès"),
("Laburnum","Cytise"),
("Elaeagnus","Eleagnus - Chalef"),
("Picea","Epicéa"),
("Acer","Erable"),
("Chamaecyparis","Faux-cyprès"),
("Fontanesia","Fontanesia"),
("Fraxinus","Frêne"),
("Halesia","Halesia"),
("Fagus","Hêtre"),
("Ilex","Houx"),
("Taxus","If"),
("Magnolia","Magnolia"),
("Aesculus","Marronnier"),
("Larix","Mélèze"),
("Metasequoia","Metaséquoia"),
("Celtis","Micocoulier"),
("Corylus","Noisetier de Byzance"),
("Non spécifié","Non spécifié"),
("Ulmus","Orme"),
("Ptelea","Orme de Samarie"),
("Parrotia","Parrotie de Perse - Arbre de fer"),
("Paulownia","Paulownia"),
("Populus","Peuplier"),
("Pinus","Pin"),
("Platanus","Platane"),
("Pyrus","Poirier à fleurs"),
("Malus","Pommier"),
("Prunus","Prunier"),
("Pterocarya","Pterocarya"),
("Robinia","Robinier"),
("Salix","Saule"),
("Koelreuteria","Savonnier"),
("Sequoiadendron","Sequoia"),
("Sophora","Sophora"),
("Sorbus","Sorbier"),
("Sambucus","Sureau"),
("Thuja","Thuya"),
("Tilia","Tilleul"),
("Ligustrum","Troene"),
("Liriodendron","Tulipier"),
("Gleditsia","Févier"),
("Ostrya","Ostryer"),
("Cornus","Cornouiller"),
("Melia","Margousier"),
("Zelkova","Zelkoua"),
("Lagerstroemia","Lilas d'été"),
("Juglans","Noyer");

