INSERT INTO Espece (Nom_scientifique_espece)
VALUES 
("altissima"),
("alba"),
("americana"),
("anagyroides"),
("angustifolia"),
("aquifolium"),
("aria"),
("aucuparia"),
("aucuparia var. edulis"),
("australis"),
("avium"),
("azedarach"),
("baccata"),
("betulus"),
("bignonioides"),
("biloba"),
("calleryana"),
("campestre"),
("capillipes"),
("cappadocicum"),
("caprea"),
("carolina"),
("carpinifolia"),
("cerasifera"),
("cerris"),
("colurna"),
("cordata"),
("daniellii"),
("davidii"),
("decidua"),
("deltoides"),
("dentata"),
("domestica"),
("dulcis"),
("excelsior"),
("flava"),
("Fleur Non spécifié"),
("floribunda"),
("fraxinifolia"),
("freemanii"),
("Fruit Non spécifié"),
("giganteum"),
("glabra Huds."),
("glutinosa"),
("glyptostroboides"),
("grandiflora"),
("hippocastanum"),
("ilex"),
("indica"),
("intermedia"),
("japonica"),
("japonicum"),
("julibrissin"),
("kobus"),
("laevigata"),
("laevis"),
("latifolia"),
("lawsoniana"),
("leylandii"),
("lucidum"),
("lusitanica"),
("maackii"),
("mas"),
("monogyna"),
("monspessulanum"),
("monticola"),
("negundo"),
("nigra"),
("nigra subsp. nigra"),
("Non spécifié"),
("occidentalis"),
("orientalis"),
("ornus"),
("padus"),
("palmatum"),
("paniculata"),
("papyrifera"),
("pendula"),
("persica"),
("phillyreoides"),
("platanoides"),
("platyphyllos"),
("plicata"),
("pseudoacacia"),
("pseudoplatanus"),
("pumila"),
("pungens f. Glauca"),
("robur"),
("saccharinum"),
("saccharum"),
("salicifolia"),
("sempervirens"),
("serrata"),
("serrula"),
("serrulata"),
("siliquastrum"),
("simonii"),
("sinensis"),
("styraciflua"),
("sylvatica"),
("sylvestris"),
("tomentosa"),
("toringoides"),
("triacanthos"),
("trichotomum"),
("trifoliata"),
("triloba"),
("trilobata"),
("tschonoskii"),
("tulipifera"),
("utilis"),
("wallichiana"),
("x atrosanguinea"),
("x canadensis"),
("x canescens"),
("x carnea"),
("x europaea"),
("x hispanica"),
("x media"),
("x schmittii"),
("x soulangeana"),
("x spaethii"),
("x subhirtella");
